sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm i -g now-pipeline
  - now-pipeline --test "npm run e2e-test" index.js package.json
  - now-pipeline prune
  - echo All good
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
